### PR TITLE
Add course's folder link in README.md

### LINKED ISSUE #24: Add link Placeholder in README file
@arv-anshul Can you include add link placeholder of each courses in main README file

### PR DESCRIPTION
**Pull request by arv-anshul**
**Fixes #24**

### CODE REVIEW

**Comment by Yash-Kavaiya** [comment]
1. Using href we can redirect
2. If we change folder name it not make much sense

**Comment by arv-anshul** [comment]
Hey, why did you closed it I can revert the commit and make the required changes 😞

**Comment by Yash-Kavaiya** [comment]
@arv-anshul Sorry but using href I redirect to respective URL
If we add course instructor is not good user experience

**Comment by Yash-Kavaiya** [comment]
@arv-anshul  I show your campusx course material website it's amazing

**Pull request closed without merging**
